### ISSUE TITLE
How to I financially support this project?

### ISSUE THREAD

**Issue by junzhengca** [dominicstop/react-native-ios-context-menu#104]
Not sure if the maintainers needs it, but just want to show my apperciation, even without documentation, the examples are comprehensive, the library is high quality.

Would love to setup some small amount of recurring donation.

**Comment by fobos531** [comment]
cc @dominicstop

**Comment by dominicstop** [comment]
hello, thank you for the kind words; i recently made a gh sponsors page: https://github.com/sponsors/dominicstop

since i’ve only created it yesterday, i won’t be able to receive a payout until october (90 days from now)

until then, i appreciate any donations ppl can spare my way
