### ISSUE TITLE
[Android] TouchableOpacity activates when releasing after long press to open ContextMenu

### ISSUE THREAD

**Issue by fredrikburmester** [dominicstop/react-native-ios-context-menu#109]
As the title says, upon releasing my finger after long-pressing an item to open the context menu the TouchableOpacity activates and the onPress action ()handleOpenFile) is executed. 

Example code: 
```
    <ContextMenu.Root>
      <ContextMenu.Trigger>
        <TouchableOpacity
          onPress={handleOpenFile}
        >
          <Text>Text</Text>
        </TouchableOpacity>
      </ContextMenu.Trigger>
      <ContextMenu.Content
        loop={false}
        alignOffset={0}
        avoidCollisions={true}
        collisionPadding={0}
      >
          <ContextMenu.Item
            key={"1"}
            onSelect={() => {}}
          >
            <ContextMenu.ItemTitle style={{ color: "red" }}>
              1
            </ContextMenu.ItemTitle>
          </ContextMenu.Item>
      </ContextMenu.Content>
    </ContextMenu.Root>
```

The expected behavior should be that he underlying TouchableOpacity does not activate. 

This is only an issue on Android it seems.

**Comment by fredrikburmester** [comment]
What is the "other lib"?

**Comment by nandorojo** [comment]
React Native Menu, https://zeego.dev wraps each one for you

**Comment by nandorojo** [comment]
If you’re having an issue on Android with Zeego, you should open an issue at `@react-native-menu`

**Comment by nandorojo** [comment]
> The expected behavior should be that he underlying TouchableOpacity does not activate.

Why? I don’t exactly agree. Why have a Pressable that shouldn’t activate?

**Comment by nandorojo** [comment]
@fredrikburmester i think we can move this issue to the zeego repo and possibly tag the react-native-menu issue as well since it’s Android
