### ISSUE TITLE
AuxiliaryPreview appears underneath ContextMenu on larger messages and is therefore blocked from being interacted with

### ISSUE THREAD

**Issue by TowhidKashem** [dominicstop/react-native-ios-context-menu#111]
Hi, first thank you for the amazing lib! It works wonderfully except one issue:

On larger messages the auxiliary view is covered by the context menu:

<img width="399" alt="Screenshot 2024-11-03 at 1 44 02 AM" src="https://github.com/user-attachments/assets/e4104558-c97f-444a-bb54-18a548efbf10">

On smaller messages it looks fine:

<img width="411" alt="Screenshot 2024-11-03 at 1 44 28 AM" src="https://github.com/user-attachments/assets/d731390f-b187-4f26-bcf5-27e26812e8c7">

**Code:**

```
<ChatBlock>
  <Wrapper>
    <ContextMenuView
      menuConfig={{
        menuTitle: '',
        menuItems: getContextMenuOptions(type)
      }}
      previewConfig={{ borderRadius: BUBBLE_RADIUS }}
      auxiliaryPreviewConfig={{
        anchorPosition: 'bottom',
        alignmentHorizontal: 'stretchScreen',
        transitionEntranceDelay: 'RECOMMENDED'
      }}
      renderAuxiliaryPreview={() => (
        <ReactionBar
          message={message}
          handleReactMessage={handleReactMessage}
        />
      )}
      onPressMenuItem={({ nativeEvent }) => {
        handleMessageLongPress(nativeEvent.actionKey, message);
      }}
      isContextMenuEnabled={!disableMenu}
    >
      <Bubble>
        {children}
      </Bubble>
    </ContextMenuView>
  </Wrapper>
</ChatBlock>
```

Is there any way to fix this or work around it? Ideally the context menu will appear anywhere else on the bubble that doesn't directly cover the auxiliary view.

**Comment by ruairioliverwv** [comment]
I had the same problem, I went with using a custom preview component. 

<img width="610" alt="Screenshot 2024-11-13 at 11 21 00" src="https://github.com/user-attachments/assets/68b7a4db-b112-4109-ba11-42a43e949e66">

**Comment by TowhidKashem** [comment]
> I had the same problem, I went with using a custom preview component.
> 
> <img alt="Screenshot 2024-11-13 at 11 21 00" width="610" src="https://private-user-images.githubusercontent.com/74560092/385734622-68b7a4db-b112-4109-ba11-42a43e949e66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMDQ3NzIsIm5iZiI6MTczMzAwNDQ3MiwicGF0aCI6Ii83NDU2MDA5Mi8zODU3MzQ2MjItNjhiN2E0ZGItYjExMi00MTA5LWJhMTEtNDJhNDNlOTQ5ZTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDIyMDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2OGZiMGFkYjBiNjE5ZTJkMTA2MTQ3Y2FmZWFmYjAwYThlYjUwNDFjZGRiMWY0OTYwMGQyNmJjMWJjMmFkMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SkK8ElcwFEO94a6u2njClP-d9gWKoZ6S3VQ_bNj4Tqg">

hey @ruairioliverwv, sorry for the late reply totally missed this! So I tried ur fix and it seems to get rid of the message bubbles entirely and replace it with the contents of the `renderPreview` prop. Is that expected? I think it kind of defeats the purpose of the auxiliary view which is to show that you are responding to a message in the first place. So it would be necessary to keep that in view but perhaps with a max height set. Or is that what you're doing? I can't tell cause I don't know what `children` is...
