### ISSUE TITLE
How to custom internal view?

### ISSUE THREAD

**Issue by chenxiang39** [dominicstop/react-native-ios-context-menu#17]
here is my target , l just want to hidden title and not have extra width

current:
![image](https://user-images.githubusercontent.com/41722774/116244798-1ef20600-a71d-11eb-952c-0a0cf00bcc05.png)

target:
![image](https://user-images.githubusercontent.com/41722774/116244850-2addc800-a71d-11eb-9fb0-b163944c385c.png)

**Comment by guytepper** [comment]
See https://github.com/dominicstop/react-native-ios-context-menu/issues/14

**Comment by chenxiang39** [comment]
> See #14

Thanks a lot !, and other question , how to let my TouchableOpcaity not transparent and add width?
![image](https://user-images.githubusercontent.com/41722774/116257825-3d5dfe80-a729-11eb-8490-316a4fd8aefe.png)

**Comment by chenxiang39** [comment]
Any one can tell me?
