### ISSUE TITLE
How to disable a ContextMenuView in a list

### ISSUE THREAD

**Issue by Kordonme** [dominicstop/react-native-ios-context-menu#20]
Let's say I have a list of items in a `FlatList` and I want to disable the `ContextMenuView` on a few of these items.

How would I go around doing that?

**Comment by nandorojo** [comment]
Couldn't you just conditionally render it?

**Comment by dominicstop** [comment]
asdfghjkdjkflsl as @nandorojo mentioned, you can also use conditional rendering (but it'll trigger a relayout, and can be potentially expensive if done repeatedly).
<br>
In the next release, I'll add add a prop called `isContextMenuEnabled` to make this easier haha (I'll close this issue once I do that).

**Comment by dominicstop** [comment]
Hey, the `ContextMenuView.isContextMenuEnabled` prop has been implemented in version [`1.7.0`](https://github.com/dominicstop/react-native-ios-context-menu/releases/tag/v1.7.0), so I'll be closing this issue now ✨
<br>
Thanks!

**Comment by Kordonme** [comment]
Wow, thanks for his @dominicstop 🚀 

And yes, I could conditionally render it, but I would still like the children of the context menu to show up. Having a boolean makes this less cluttered for me as a developer. @nandorojo

**Comment by nandorojo** [comment]
> but I would still like the children of the context menu to show up

I agree it's a nicer DX with the Boolean, but that's still possible FWIW:

```js
let Wrapper = React.Fragment
let wrapperProps = {}
if (isMenu) {
  Wrapper = ContextMenu
  wrapperProps = {...propsHere}
}

return <Wrapper {...wrapperProps}>{children}</Wrapper>
```
