### ISSUE TITLE
Context Preview Menu that doesn't close on tap.

### ISSUE THREAD

**Issue by henrymoulton** [dominicstop/react-native-ios-context-menu#21]
Hi @dominicstop,

Really love the library, is it possible to have a Preview that doesn't close on tap, instead it contains Touchables that when pressed will do various thing?

**Comment by dominicstop** [comment]
asdfghjksjhslkkl, I did some testing in the past and I couldn't get this to work (the preview isn't interactive, and doesn't receive touch-events no matter what I do).
<br>
Maybe this will change in a future iOS version, but atm there's nothing I can do sadly.
