### ISSUE TITLE
requirenativecomponent: "RCTContextMenuView" was not found in the uimanager

### ISSUE THREAD

**Issue by musetraine** [dominicstop/react-native-ios-context-menu#22]
requirenativecomponent: "RCTContextMenuView" was not found in the uimanager, I think it is can be because EXPO, and I don't know what can I do with it, maybe some solution?
![Снимок экрана 2021-09-01 в 11 19 30](https://user-images.githubusercontent.com/18230499/131637762-c1509092-acf2-4bed-80f3-05a9f6af3b5a.png)

**Comment by dominicstop** [comment]
asdfghjkljjkjksjf sorry for the late reply, let me look into it haha

**Comment by dominicstop** [comment]
Hey, installed this library on expo bare workflow (version `43.0.2`) and it seems to work okay? I just installed it + ran `pod install` and worked without any issues.
<br>
![Screen Shot 2021-11-30 at 11 35 55 AM](https://user-images.githubusercontent.com/18517029/143981626-f17d4c40-fea0-4216-ab05-2185c9a39d18.png)
<br>
I'll be closing this issue now, thanks!
