### ISSUE TITLE
PrecompileSwiftBridgingHeader error while building for simulator in debug mode

### ISSUE THREAD

**Issue by adhip94** [dominicstop/react-native-ios-context-menu#23]
Hi,

So I always get this error while building my application for **iOS** in **debug** mode in **simulator only**.

```
<unknown>:0: error: module map file '/Users/developer/Library/Developer/Xcode/DerivedData/mobileapp-dtygbbxyzwnkvmbbcgvdxgrbooef/Build/Products/Debug-iphonesimulator/react-native-ios-context-menu/react_native_ios_context_menu.modulemap' not found
Command PrecompileSwiftBridgingHeader emitted errors but did not return a nonzero exit code to indicate failure
```

I don't face any issues while building for release mode in simulator or for the actual device in both release and debug mode. I am using Xcode 12.5.1 and running RN 0.65.1, I was facing this issue in RN 0.64.2 as well. 

Anyone knows how to resolve this?

**Comment by dominicstop** [comment]
asdfghjkdsffljkl ok so this library is written in swift so there's some extra steps involved to make it work on react-native.
<br>
I'm gonna do some debugging, but in the meantime:
1. Have you tried adding an [empty swift file](https://github.com/dominicstop/react-native-ios-context-menu/blob/master/README-next.md#troubleshooting-xcode-build-error-swift)?
2. Have you tried modifying the project's[ library search paths](https://github.com/dominicstop/react-native-ios-context-menu/blob/master/README-next.md#troubleshooting-xcode-build-error-undefined-symbol)?

**Comment by dominicstop** [comment]
Hey, installed this library on expo bare workflow (version `43.0.2`) and it seems to work okay? I just installed it + ran `pod install` and worked without any issues.
<br>
![Screen Shot 2021-11-30 at 11 35 55 AM](https://user-images.githubusercontent.com/18517029/143981626-f17d4c40-fea0-4216-ab05-2185c9a39d18.png)
<br>
I'll be closing this issue now, thanks!
