### ISSUE TITLE
Nested `ContextMenuView` triggers `onPressMenuItem` for each context menu view

### ISSUE THREAD

**Issue by Kordonme** [dominicstop/react-native-ios-context-menu#27]
Having a `ContextMenuView` inside another `ContextMenuView` will trigger `onPressMenuItem` for both of the components when triggered for the inner component.
However, the UI works as expected. I'm not sure of this is really an issue, but I would like some feedback on how to handle this use case.

**Comment by dominicstop** [comment]
asdfghnjmjjklkl seems like an event propagation bug (oops, i'll fix it in the next minor version).

Hopefully this gets fixed by simply calling `e.stopPropagation()` on the event object 😔.

**Comment by dominicstop** [comment]
asdfghjkljkljkl did some testing and it does get fixed by just calling `event.stopPropagation()`

https://user-images.githubusercontent.com/18517029/141603999-76f56e30-fc00-4bc2-a652-1e73ecf347fd.mov

**Comment by dominicstop** [comment]
Hey there, I fixed this in the newest release (`1.4.0`) ✨. 
If the bug is still present, please let me know, and I'll re-open this issue asdfghjkljklklsdfgjkl

**Comment by Kordonme** [comment]
Wow, it works. Thank you so much for the quick fix and release! And thank you so much for your hard work!
