### ISSUE TITLE
Duplicate interface definition for class 'RCTSwiftLog'

### ISSUE THREAD

**Issue by raphaelrk** [dominicstop/react-native-ios-context-menu#3]
Was getting the following error when building with this library: `Duplicate interface definition for class 'RCTSwiftLog'`.

I'm assuming it's because react-native-ios-modal, which I also installed, also creates RCTSwiftLog.

I commented out the .h, .m, and .swift for RCTSwiftLog in this library and things started compiling for me again. Maybe there's a way to only declare RCTSwiftLog once between the two.

**Comment by dominicstop** [comment]
I'm gonna try making the classes private, maybe it'll fix it? (Or change the names as a temp. fix 🤣)

I'll try and find a solution haha

**Comment by dominicstop** [comment]
@raphaelrk hello! i've published a patch, it should be fixed now 😊
(please let me know if you have any other issues)

**Comment by raphaelrk** [comment]
Wow that was so fast!! Thank you @dominicstop 😊
