### ISSUE TITLE
Navigating back to screen from e.g. screen A -> B -> A causes ContextMenuView to disappear from this.props.navigation.navigate

### ISSUE THREAD

**Issue by ethan1141** [dominicstop/react-native-ios-context-menu#30]
https://user-images.githubusercontent.com/53418441/147514124-c4168bdc-9a65-4c31-80fd-d4e15c046378.mp4

`<Pressable style={styles.row} onPress={() => { this.props.navigation.navigate("View Note", { note: item } ); }}>
                         <ContextMenuView   onPressMenuItem={({nativeEvent}) => {
    alert(`onPressMenuItem nativeEvent: ${JSON.stringify(nativeEvent)}`)
  }} menuConfig={{
                             menuTitle: 'Actions',
                                 menuItems: [{
                                     actionTitle: 'Delete',
                                     actionSubtitle: 'Delete me!',
                                     actionKey: '1',
                                 }]
                             }}>
                            <View style={{paddingVertical: 5, flexDirection:"row"}}   >
                                 <Text style={{flex:1}}>{item.subject} </Text> 
                                 <Text style={{marginRight:15}}>{item.date}</Text>  
                            </View>
                            <Text>{item.note.slice(0, 100) + (item.note.length > 100 ? "..." : "")}</Text>
                        </ContextMenuView>
                            <View style={{paddingVertical: 5, flexDirection:"row"}}   >
                                 <Text style={{flex:1}}>{item.subject} </Text> 
                                 <Text style={{marginRight:15}}>{item.date}</Text>  
                            </View>`

**Comment by ethan1141** [comment]
it is essentially destroying itself

**Comment by marcosrdz** [comment]
I downgraded the package to avoid this issue.

**Comment by adorum** [comment]
same issue here. Event downgrade to 1.7.1 or 1.7.0 didn't help. Any suggestions?

**Comment by marcosrdz** [comment]
> same issue here. Even downgrade to 1.7.1 or 1.7.0 didn't help. Any suggestions?

I was on 1.3.0 prior to updating to 1.7.2 and seeing this issue. Went back to 1.3.0

**Comment by adorum** [comment]
Latest working version is 1.4.0

**Comment by dominicstop** [comment]
asafgdhjskjkl sorry I just saw this — it turns out, whenever a new screen is pushed, `didMoveToWindow` gets called, triggering the cleanup process haha (working on a quick fix right now)



![image](https://user-images.githubusercontent.com/18517029/151275525-ebd973d1-b1b3-4e72-aac7-9a4c6016cdc2.png)

**Comment by dominicstop** [comment]
Hey sorry this took so long, but i fixed this in [v1.7.4
](https://github.com/dominicstop/react-native-ios-context-menu/releases/tag/v1.7.4) — this patch contains native code changes, so please don't forget to run `pod install` after updating ✨

please let me know if there are still problems and I'll re-open the issue — I haven't tested this thoroughly so there might be some edge-cases I've forgotten to consider (e.g. modals, interactive animations, etc).

**Comment by ethan1141** [comment]
Much appreciated, I will take a look

**Comment by dominicstop** [comment]
@tryheirloom-matheus let me take a look haha (i tested it with a min. working example with just a single screen though, but maybe there are some edge cases)

in the meantime, have you run `pod install`? I made some changes in the native side (maybe it hasn't been applied yet when you updated?)

**Comment by tryheirloom-matheus** [comment]
> @tryheirloom-matheus let me take a look haha (i tested it with a min. working example with just a single screen though, but maybe there are some edge cases)
> 
> in the meantime, have you run `pod install`? I made some changes in the native side (maybe it hasn't been applied yet when you updated?)

thanks @dominicstop! yes, I ran it :)
- react-native-ios-context-menu (1.7.4):

**Comment by projodesign** [comment]
I've found an edge case - if opening a <Modal> that has presentationStyle="fullScreen" as a prop then the ContextMenuButton disappears on the screen where the modal was called from. "fullScreen" is also the default if no presentationStyle is omitted and the issue also occurs in this scenario.

It seems OK with the other presentationStyles - for me using "overFullScreen" works the same as "fullScreen" and the issue does **not** occur - so is a suitable workaround for now.

**Comment by pfcodes** [comment]
> I've found an edge case - if opening a that has presentationStyle="fullScreen" as a prop then the ContextMenuButton disappears on the screen where the modal was called from. "fullScreen" is also the default if no presentationStyle is omitted and the issue also occurs in this scenario.
> 
> It seems OK with the other presentationStyles - for me using "overFullScreen" works the same as "fullScreen" and the issue does **not** occur - so is a suitable workaround for now.

This is a good catch. I'm having this issue with React Navigation `Stack.Group` with `presentation` set to `fullScreen`. Unfortunately React Navigation has no `overFullScreen` option. This issue should be reopened.
