### ISSUE TITLE
Make menu title optional

### ISSUE THREAD

**Issue by matheusmichels** [dominicstop/react-native-ios-context-menu#33]
Hey @dominicstop, first of all, thank you so much for this package!

As far as I know, most part of the apps that use the UI Context Menu don't have a title for it (e.g. 
https://www.appcoda.com/wp-content/uploads/2019/09/context-menu-maps-photos-1024x709.png). What do you think about setting the title as optional?

**Comment by dominicstop** [comment]
hello! i'm just mirroring the [`UIMenu`](https://developer.apple.com/documentation/uikit/uimenu/3358594-init) API and it requires the menu title to be set haha
```
UIMenu.init(title:image:identifier:options:children:)
```

you can always just pass in an emoty string though if you don't need a menu title:
![Screen Shot 2022-02-02 at 6 14 40 AM](https://user-images.githubusercontent.com/18517029/152060471-d3513b9e-e6f6-483e-ba0f-89c653fb790b.png)

before i make this optional, i just need to check if any native code breaks if I do this ✨
