### ISSUE TITLE
Opening and closing menu freezes screen

### ISSUE THREAD

**Issue by intergalacticspacehighway** [dominicstop/react-native-ios-context-menu#35]
Hey dominic. We're facing a weird issue that happens only on a release build. Even more weird is that it's not reproducible on building with release scheme on XCode.

Steps:
- Open menu
- Close it by swiping anywhere in screen (don't tap or select menu item)
- Any Pressable element on screen don't respond until we open or close the menu again

I can't share a reproducible demo, because I am not able to reproduce it either in my local environment, even with release scheme 😞. I know it's hard to track the issue, let me know if you've seen something like this previously. [This issue](https://github.com/dominicstop/react-native-ios-context-menu/issues/9) looks similar, but we're using a simple menu and we don't have any Pressable element as children.

Also, observed this issue which looks a bit similar. (happens only on production build)
- Open menu
- Put the app in background
- Come back to app, can't tap or scroll anything

Thanks. I'll update the issue If I find something :)

**Comment by dominicstop** [comment]
oops, let me take a look — i only use `TouchableOpacity` (out of habit) so i never came across this (going to write a small example to test this out)

i'll post a patch ASAP once i find the bug

**Comment by intergalacticspacehighway** [comment]
Thanks, Dominic. This seems to be unrelated to this library. I still haven't been able to repro the issue locally even with the release build but the same issue happens with react-native-menu's menu 😞. I will update if I find something. Closing this.

**Comment by dominicstop** [comment]
i'm going to try and release a quick patch — there's some leftover experimental code/wip features in the release version, i'll commenting them out, maybe it'll fix it haha

**Comment by intergalacticspacehighway** [comment]
No worries @dominicstop I just figured it out. The issue was with the LogRocket library being used in production. Your library is awesome. Thank you again! :)
