### ISSUE TITLE
Expo config plugin

### ISSUE THREAD

**Issue by pepyta** [dominicstop/react-native-ios-context-menu#36]
Hey! I think that it would be awesome to have this package available in managed workflow.

As of Expo SDK 41+, there is a feature called "Config Plugins", which gives developers an opportunity to create custom dev client for their Managed workflow apps with custom native code in it.

[https://docs.expo.dev/guides/config-plugins/](https://docs.expo.dev/guides/config-plugins/)

**Comment by i-ira** [comment]
> Hey! I think that it would be awesome to have this package available in managed workflow.
> 
> As of Expo SDK 41+, there is a feature called "Config Plugins", which gives developers an opportunity to create custom dev client for their Managed workflow apps with custom native code in it.
> 
> https://docs.expo.dev/guides/config-plugins/

+1

**Comment by brentvatne** [comment]
this shouldn't be necessary, there are no additional config steps after installing the library
