### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by robertherber** [dominicstop/react-native-ios-context-menu#37]
I noticed there's [another library](https://github.com/mpiannucci/react-native-context-menu-view) that's not as fully featured as this one - but it offers Android support through `PopupMenu`. Do you have any plans of doing something similar?

**Comment by fukemy** [comment]
waiting for ur answer too

**Comment by fukemy** [comment]
@dominicstop plz help

**Comment by robertherber** [comment]
@fukemy I noticed there’s another new library that might be worth checking out (haven’t had time to try it though) with cross-platform support https://github.com/nandorojo/zeego

**Comment by Flam3rboy** [comment]
@robertherber `zeego` uses this library under the hood for ios

**Comment by fukemy** [comment]
hi @Flam3rboy , i dont know why #zeego can use this library while it's expo support only.

About Android, while no solution for nice context menu, so I decided to create a reaction button beside message like Viber. But I still waiting for great solution in Android

**Comment by robertherber** [comment]
@Flam3rboy I've started using zeego as well and it works great. Using it is probably the best solution: This library can focus on being an enabler for deeper iOS features while zeego can be the cross-platform abstraction layer.

I'll close this, [zeego](https://github.com/nandorojo/zeego) is the answer for cross-platform support.
