### ISSUE TITLE
Open a context menu programmatically

### ISSUE THREAD

**Issue by matheusmichels** [dominicstop/react-native-ios-context-menu#40]
Hey @dominicstop! I'm really enjoying this library, thanks so much for your work on it!
I think one great thing to add would be the ability to open a context menu programmatically/imperatively.
The API could be something like this:
```typescript
const event = await UIContextMenu.open(exampleNodeId, menuConfig)
```
Or
```typescript
UIContextMenu.open(exampleNodeId, menuConfig, event => {
   // Handle menu item press event
})
```

What do you think? 😎

**Comment by nandorojo** [comment]
A better API would be:

```ts
const ref = useRef()

const onPress = () => ref.current?.open()

return <ContextMenuView ref={ref} />
```

**Comment by pfcodes** [comment]
Much needed

**Comment by nandorojo** [comment]
iOS does not allow this for context menus, so I think it's worth closing.
