### ISSUE TITLE
Support preview view( like reaction...) like message,...

### ISSUE THREAD

**Issue by fukemy** [dominicstop/react-native-ios-context-menu#41]
Hi, thanks for great lib
As u can see the picture here, did u support to show a custom preview include reaction? Thanks

![image](https://user-images.githubusercontent.com/8202437/170690068-be804c0e-3eee-40c7-921d-d47dbb5e1361.png)

![image](https://user-images.githubusercontent.com/8202437/170690121-28141e45-d1a8-46ad-8817-24e67ebcb585.png)

**Comment by Flam3rboy** [comment]
duplicate of #31

**Comment by fukemy** [comment]
tks
