### ISSUE TITLE
Context menu flickering(may be it re-render) after modify message data

### ISSUE THREAD

**Issue by fukemy** [dominicstop/react-native-ios-context-menu#43]
Hi, i just found this problem. it's REALLY HARD TO KNOW. 

you can see the video here, as I just add a reaction to view:

https://user-images.githubusercontent.com/8202437/174272591-80fdb8cc-c6eb-4c04-baa2-15015bcbfee8.mov

Here is the main layout for view:

```
<ContextMenuView>
   <Bubble/>
  <ReactionView/>
</ContextMenuView>
```

Inside onPressMenuItem, i just update message:

```
const message = props.currentMessage
                            const reactions = message.reactions
                            reactions.push({
                                'id': '1',
                                'type': 200,
                                'date': new Date().getTime(),
                                'by': currentUser.id
                            })
                            message.reactions = reactions
                            handleChoosenMessageReaction(message)

```

```
const handleChoosenMessageReaction = React.useCallback((message) => {
        const newMessages = [...messages]
        const index = newMessages.findIndex(mes => mes._id === message._id)
        console.log('index', index)
        if(index > -1){
            newMessages[index].reactions = [...message.reactions]
            console.log('handleChoosenMessageReaction', message.reactions)
            setMessage(newMessages)
        }
    })
```
I tried to use https://github.com/mpiannucci/react-native-context-menu-view but it's does not make problem, But I want to use your lib because it's better

Please helppp

**Comment by fukemy** [comment]
@dominicstop plz help bro

**Comment by fukemy** [comment]
I have tested with assets image, text bubble, it's still flickering 

I tried to update message inside Image touch(without show context menu), it's work, The flick only show when context menu action

**Comment by dominicstop** [comment]
Let me take a look

but i need to know a few things first so i can reproduce the bug:
* react-native version
* library version
* iOS version
* Running on: Debug or Production
* Running on: Simulator or Device

**Comment by fukemy** [comment]
Hi, I just change update message function inside ***onMenuDidHide***:
```
onMenuDidHide={() => {
                            console.log('onMenuDidHide')
                            const message = props.currentMessage
                            const reactions = message.reactions
                            reactions.push({
                                'id': '1',
                                'type': 200,
                                'date': new Date().getTime(),
                                'by': currentUser.id
                            })
                            message.reactions = reactions
                            handleChoosenMessageReaction(message)
                        }}
```
Then it's work without any problem, you can see the video here:

https://user-images.githubusercontent.com/8202437/174275009-c2cdad4b-69f4-4667-b105-25f77237611f.mov

THanks god, I can reproduce case of bug, may be I tried to update state when the time animation running

react-native version: "^0.68.0",
library version: "^1.8.0"
iOS version : 15.5
Running on: Production // i change build mode to production
Running on: Simulator


Please help

**Comment by dominicstop** [comment]
@fukemy  Hey, I've added [`Test02Screen`](https://github.com/dominicstop/react-native-ios-context-menu/blob/7dbf32229d0dec0ef04c86a0ec0d0e218355ef71/example/src/screens/Test02Screen.tsx) to reproduce your bug.

https://user-images.githubusercontent.com/18517029/174292418-a660a28a-86a9-43a3-b33a-51f35ef43160.mov

<br>

As a temp. solution, I'm going to update `onPressMenuItem` so that it fires after the context menu is hidden first 

Once i finish releasing the patch, I'll close this issue 😌

**Comment by fukemy** [comment]
yeah, love u bro

**Comment by fukemy** [comment]
sorry i will let u close this issue :3
