### ISSUE TITLE
bug: crashes with xcode beta

### ISSUE THREAD

**Issue by Flam3rboy** [dominicstop/react-native-ios-context-menu#46]
> // Note: Xcode beta + running on device (iPhone XR + iOS 15.1) causes
    // crashes when the context menu is being created

As commented in the file [RNIContextMenuView.swift](https://github.com/dominicstop/react-native-ios-context-menu/blob/master/ios/src/ReactNative/RNIContextMenuView/RNIContextMenuView.swift#L1099-L1105) the app crashes when I'm trying to open the context menu.
Is there any fix for this issue?

Environment:
- macOS 12.4
- iOS 16.0
- react-native 0.68.2
- react-native-ios-context-menu 1.11.0
- Xcode 14.0 beta (14A5228q)

**Comment by dominicstop** [comment]
Hi! This is a bug/known issue with XCode beta ([link to release notes](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-16-release-notes))

>UIKit
> Known Issues
> Swift apps that reference UIContextMenuConfiguration and are compiled with the iOS 16 beta SDK crash on launch when run on a device running an older build. (93505538)
