### ISSUE TITLE
[HELPPPPPP] get click event from ContextMenuView

### ISSUE THREAD

**Issue by fukemy** [dominicstop/react-native-ios-context-menu#47]
Hi, i want to handle click into ContextMenuView, because my keyboard + textInput need some calculated code, 
when click outside of ContextMenuView( it's mean i return ContextMenuView from renderItem with FlatList) => i can handle it

As you can see video here:

https://user-images.githubusercontent.com/8202437/180963326-ede2c648-38b1-4a91-846f-9efc9d126506.mov

But when click into ContextMenuView, i can catch click event, so. the input not go down.
i tried to use
```
 <ContextMenuView
                        keyboardShouldPersistTaps='never'
                        onPress={...}
                        onLongPress={...}
```

Plz help my problem

**Comment by fukemy** [comment]
im sure the problem is ***ContextMenuView click***, because when remove ContextMenuView, it work normally

**Comment by dominicstop** [comment]
@fukemy let me look into it, but i have to make a test case first so i can debug the issue

tbh, i'm not really sure what's wrong — it's a layout issue related to the keyboard right? could you describe it in more detail?

**Comment by dominicstop** [comment]
hey i made a test case for your issue: [`Test03Screen`](https://github.com/dominicstop/react-native-ios-context-menu/blob/master/example/src/screens/Test03Screen.tsx)

https://user-images.githubusercontent.com/18517029/182884608-0211d1fb-012a-4076-9afe-9fbdefdfaffa.mov

<br>

but i couldn't reproduce the bug...
if you're still having issues, i'll reopen this 😊

**Comment by timothyerwin** [comment]
@dominicstop is it a performance issue that it is rendering the context menu for each message bubble in a flat list? 

if there are hundreds of messages for example. what I mean is, it seems like it would be better if the long press triggered a context menu on demand as opposed to adding it in the tree for each message?
