### ISSUE TITLE
how to close context menu by click into AuxiliaryPreview?

### ISSUE THREAD

**Issue by fukemy** [dominicstop/react-native-ios-context-menu#49]
Hi, i want to display AuxiliaryPreview as message reaction, click to choose reaction then close context menu, but in document i didnt see any method related, can u help?

**Comment by dominicstop** [comment]
Hi, you can can programmatically close the context menu via calling `dismissMenu`.

Search for the keyword "dismiss" in the docs, or take a look at [`ContextMenuView` Test 08](https://github.com/dominicstop/react-native-ios-context-menu#contextmenuview-test-08) for some example code + gif.

hope this helps, xx

**Comment by fukemy** [comment]
thanks, it's worked
