### ISSUE TITLE
Menu dark mode.

### ISSUE THREAD

**Issue by imyuanx** [dominicstop/react-native-ios-context-menu#52]
I have a basic menu. I cannot actively activate the dark mode, but it can successfully respond to the system dark mode.
So can we actively activate the dark mode?

**Comment by dominicstop** [comment]
i'm planning on implementing this on a future version — i just need to finish a few things first before I can begin working on it ✨

I'll close this issue once I'm done adding it

**Comment by yunying1** [comment]
Thanks for your excellent work!

**Comment by nandorojo** [comment]
Controlled dark mode would be awesome @dominicstop, thanks for working on it!

**Comment by luoxuhai** [comment]
@nandorojo You can try using [`react-native-override-color-scheme`](https://github.com/plumvillage/react-native-override-color-scheme)

**Comment by nandorojo** [comment]
Looks like dark mode works now. And I think you can override it as of RN 0.72 with `Appearance` from react-native directly.

**Comment by atambo** [comment]
I'm finding that the ContextMenu does not seem to be following the appearance override. It seems like the ContextMenu just always follows the system settings right now. @nandorojo
