### ISSUE TITLE
Remote images

### ISSUE THREAD

**Issue by nandorojo** [dominicstop/react-native-ios-context-menu#55]
@dominicstop is there a way to use remote images from a URL? I know we can use `resolveAssetSource` for local images, but it would be cool to have an API for remote images too if possible.

**Comment by dominicstop** [comment]
afahgsjdhdkfjdk maybe there's some way i can reuse `RCTImage`'s remote image loading logic?

i'll look into it, and update this issue

**Comment by dominicstop** [comment]
Did some initial testing, and it should be doable asfdghsjdkls;gdfskfks

![Screen Shot 2022-09-26 at 2 50 07 AM](https://user-images.githubusercontent.com/18517029/192160274-3e62809a-3552-4105-8fe4-2477ae9bb8b0.png)

i'll close this issue once i've fully implemented it

**Comment by nandorojo** [comment]
awesome!!

**Comment by dominicstop** [comment]
Hi, i've impl. this in the latest release (i.e. version `1.13.0`), so i'll be closing the issue now asdfgvhdsfjsdbjksvfhewfw

i haven't added the documentation yet, so please refer to [`ContextMenuViewExample26`](https://github.com/dominicstop/react-native-ios-context-menu/blob/master/example/src/examples/ContextMenuViewExample26.tsx) for now ✨

https://user-images.githubusercontent.com/18517029/192527402-1dd82c7f-2635-407d-b3da-18ac92340616.mp4

**Comment by nandorojo** [comment]
Wow amazing work, thanks for doing this so quickly.
