### ISSUE TITLE
`TypeError: null is not an object (evaluating 'RNIUtilitiesModule.initialize')`

### ISSUE THREAD

**Issue by nandorojo** [dominicstop/react-native-ios-context-menu#57]
```js
TypeError: null is not an object (evaluating 'RNIUtilitiesModule.initialize')
/node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
/node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
/node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
/node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
/node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
/node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
```

I'm getting this error on `1.14.0`, from these new changes: https://github.com/dominicstop/react-native-ios-context-menu/commits/3d112239b2a9aa8406a61032aa60abd51844aeb2/src/native_modules/RNIUtilitiesModule.ts

For some reason, it isn't finding these native modules, even after running `pod install`. I wonder if there are any good ways to debug?

**Comment by peterferguson** [comment]
hey @nandorojo, how did you fix this? 

Currently running into this using zeego

**Comment by nandorojo** [comment]
be sure to rebuild the dev client and not use expo go

**Comment by peterferguson** [comment]
Cheers just had to rebuild my dev client 👍
