### ISSUE TITLE
Support new React Native Architecture

### ISSUE THREAD

**Issue by nandorojo** [dominicstop/react-native-ios-context-menu#64]
It would be great to support the New Architecture for Fabric/JSI. I think the easiest way to do this would be to use Expo's new Swift API. What do you think @dominicstop?

**Comment by nandorojo** [comment]
Also mentioned at #60

**Comment by AnushavanGhulyan-melon** [comment]
I am also waiting for new architecture support.
Any news @dominicstop ?

**Comment by BartoszFicek** [comment]
@dominicstop any news about New Architecture?

**Comment by nandorojo** [comment]
This is in progress now as the library is migrating to Expo Modules.
