### ISSUE TITLE
Crash when closing ContextMenuView: [__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]

### ISSUE THREAD

**Issue by mozzius** [dominicstop/react-native-ios-context-menu#70]
Trying to upgrade to Expo 49, and now when trying to close my ContextMenuViews, the app crashes.

<img width="170" alt="Screenshot 2023-06-29 at 17 03 33" src="https://github.com/dominicstop/react-native-ios-context-menu/assets/10959775/c60f7d1c-84bd-4bd8-b574-5ac07a25c3c5">

**Comment by czamp** [comment]
I'm getting the same error after upgrading my project to Expo 49, as well, and it's not present when I remove references to this library.

Any luck with a workaround?

**Comment by mozzius** [comment]
bizarrely, it stopped happening to me, and I'm not sure when (since I stopped trying to use them while I thought it would crash the app). sorry I can't be more help than that :(

**Comment by TomWq** [comment]
I'm getting the same error after upgrading my project to Expo 49, as well, and it's not present when I remove references to this library.

Any luck with a workaround?

**Comment by peterferguson** [comment]
Getting this as well but it only happens if the component in `renderAuxiliaryPreview` uses `react-native-reanimated`

**Comment by nandorojo** [comment]
Same, I think removing reanimated fixed it for me

**Comment by nandorojo** [comment]
Upgrading would make sense as the fix, as I also have not seen this error on RN 0.72.5. I'm going to close this issue, but if someone can confirm it still happens on RN 0.72.5 after removing reanimated from the auxiliary, we can reopen.

**Comment by nandorojo** [comment]
Reopening as it's happening to us on RN 0.75

**Comment by nandorojo** [comment]
![IMG_5101](https://github.com/dominicstop/react-native-ios-context-menu/assets/13172299/b6e46db0-c731-438b-91ef-448b91c64b34)

**Comment by nandorojo** [comment]
This is kind of weird but, quitting the Expo dev client entirely and reopening it seems to have fixed it. But refreshing Metro did not. So I'm wondering if there is a memory issue related...I'll try the new v2 and see how that goes.

**Comment by nandorojo** [comment]
Are people still getting this error?

**Comment by valentinchelle** [comment]
> Are people still getting this error?

I believe this issue is still occurring on RN `0.73.2`

**Comment by focux** [comment]
Yes, I'm on 0.73.1 and still getting this error.

**Comment by focux** [comment]
FYI, what fixed this for me was to wrap the children of the `ContextMenuView` inside a `View`. I was using FlashList and looks like the recycling was causing to remove and add the children of the context menu.

**Comment by whalemare** [comment]
Has same issue on 1.6.2 (non-expo)

```
    "react-native-ios-context-menu": "1.6.2",
    "react-native": "0.74.1",
```


```typescript
      <View style={{ flexDirection: 'row', gap: 8 }}>
        {item.images.map(image => {
          return (
            <ContextMenuView
              key={image.id}
              // menuConfig={{
              // menuTitle: 'BasicUsageExample01',
              // menuItems: [
              //   {
              //     actionKey: 'key-03',
              //     actionTitle: 'Action #3',
              //   },
              // ],
              // }}
              previewConfig={{
                previewType: 'CUSTOM',
                previewSize: 'INHERIT',
              }}
              renderPreview={() => {
                return (
                  <View>
                    <ImageView style={{ width: 400, height: 400 }} url={image.original} />
                  </View>
                )
              }}
            >
              <View>
                <ImageView style={{ width: 100, height: 100 }} url={image.thumbnail} />
              </View>
            </ContextMenuView>
          )
        })}
      </View>
```
