### ISSUE TITLE
☂️ v2 Stability

### ISSUE THREAD

**Issue by nandorojo** [dominicstop/react-native-ios-context-menu#77]
Here's an umbrella issue for v2. Please list any problems with it here.

# Bugs 

- [x] Pressables inside of a context menu firing navigation in a native stack cause a crash
- [x] Auxiliary view isn't pressable #66
- [x] Sometimes `dismissMenu` doesn't work (unpredictably) but this is from v1. Not sure if this is still a problem on v2 or not.

# Breaking Changes

- [ ] Automatically map v1 auxiliary props to v2 native auxiliary props to avoid breaking changes.

# Features 

- [ ] Explore double-tap to open a reaction like iMessage's "Tapback" feature

**Comment by dominicstop** [comment]
Current working on: 
* 02 - Auxiliary view isn't pressable
* Branch: [fix-issue#77-02](https://github.com/dominicstop/react-native-ios-context-menu/tree/fix-issue%2377-02)

**Comment by nandorojo** [comment]
Great! Be sure to make the pressable navigate to another screen in a react navigation native stack.

**Comment by dominicstop** [comment]
* Item: 01 - Pressables inside of a context menu firing navigation in a native stack cause a crash
* Status: Fixed (to be merged to main + publish patch)


https://github.com/dominicstop/react-native-ios-context-menu/assets/18517029/967ec184-6609-4f50-ba80-666567bb35da

**Comment by nandorojo** [comment]
@dominicstop Regarding #73, I think that issue was caused by Zeego. I just removed it from FlashList and I'm no longer facing #73. 

Could we try to fix #66 instead? I believe this issue got added from v2.

**Comment by dominicstop** [comment]
* Currently working on: item-03 -  Sometimes dismissMenu doesn't work (unpredictably) but this is from v1. Not sure if this is still a problem on v2 or not.
* Branch: TBA

**Comment by dominicstop** [comment]
* Currently working on: item-04: Features - Explore double-tap to open a reaction like iMessage's "Tapback" feature
* Branch: TBA

**Comment by focux** [comment]
First, thank you for all the work you put into this lib, it's amazing.

Also, is there any progress on the double-tap feature?
