### ISSUE TITLE
Auxiliary preview jump paired with adjustKeyboardInsets on FlatList

### ISSUE THREAD

**Issue by morajabi** [dominicstop/react-native-ios-context-menu#78]
After settings this property on FlatList and having a textInput with `<InputAccessoryView>` rendered below the list this behaviour is observed (see video)

Code:
```
<>
  <FlatList 
     automaticallyAdjustKeyboardInsets={true}
  />
  <InputAccessoryView>
     <TextInput />
  </InputAccessoryView>
</>
```

https://github.com/dominicstop/react-native-ios-context-menu/assets/12202757/b132d55e-1597-411f-a5ed-5a1ad1983f99

**Comment by hirbod** [comment]
This is a known problem with InputAccessoryView. Best would be to use [react-native-keyboard-controller](https://github.com/kirillzyusko/react-native-keyboard-controller) instead to build the sticky navbar. InputAccessoryView also hides on page navigation and it also hides if you trigger `alert`. Its really terrible and you should avoid using it

**Comment by nandorojo** [comment]
Good to know thanks, I’ll close this then. Classic RN built-in components being broken.
