### ISSUE TITLE
Type Definitions (TypeScript)

### ISSUE THREAD

**Issue by mrousavy** [dominicstop/react-native-ios-context-menu#8]
Hi @dominicstop !

First off, I have to say I really love your library. I've had a hard time with a similar library, but yours works a lot better for my use case.
A big downside for me are the missing Types (`.ts`/`.d.ts`) and type definitions for TypeScript, as I am using TypeScript for my whole project, and now this single library is emitting warnings since there are no types here.

Could you maybe consider adding types if you have some free time available?

Thank you!

**Comment by Kordonme** [comment]
I'd happily create a PR, but will it be reviewed and merged? Not much activity lately @dominicstop

**Comment by nandorojo** [comment]
I've been slowly adding my own types

```ts
type MenuOption = 'destructive' | 'displayInline'
type MenuAttribute = 'disabled' | 'destructive' | 'hidden'

type MenuAttributes = MenuAttribute[]
type MenuOptions = MenuOption[]

type MenuConfig = {
  menuTitle: string
  menuItems: (MenuItem | MenuConfig)[]
  menuAttributes?: MenuAttributes
  menuOptions?: MenuOptions
  icon?: MenuItemIcon
}

type MenuItemIcon =
  | {
      iconType: 'SYSTEM'
      iconValue: string
    }
  | {
      iconType: 'REQUIRE'
      iconValue: unknown
    }

type MenuItem = {
  actionKey: string
  actionTitle: string
  discoverabilityTitle?: string
  menuAttributes?: MenuAttributes
  menuOptions?: MenuOptions
  icon?: MenuItemIcon
  menuState?: 'on' | 'off' | 'mixed'
}
```

I'm not sure if there are plans to maintain the library again. I hope so, because it's one of the best native libs I've come across.

**Comment by Kordonme** [comment]
It looks like types are included in latest version (`1.4.0`). I just can't seem to get them to work. Is this just me?

**Comment by dominicstop** [comment]
Hey @Kordonme ✨

I created a new fresh project, and installed the package and the type annotation seems to work ok? 

![image](https://user-images.githubusercontent.com/18517029/141791248-42345612-3de7-471a-a09b-7fe34914bcbc.png)

asdfghjkljkljklkjklshjdgk maybe try uninstalling and installing the package again? (and maybe clearing the cache?) idk why, but sometimes the type annotations don't immediately show up in VSCode (i've encountered this same problem before)

**Comment by nandorojo** [comment]
Thank you @dominicstop!!

**Comment by dominicstop** [comment]
Finished re-writing the [examples](https://github.com/dominicstop/react-native-ios-context-menu/tree/master/example/src/examples) to typescript (now i just need to finish re-writing the documentation 😔).

So I'm closing the issue now ✨
