### ISSUE TITLE
presentMenu not working in some versions of iOS

### ISSUE THREAD

**Issue by zeta-gc** [dominicstop/react-native-ios-context-menu#90]
I'm having problems with the presentMenu function, in some versions of iOS when the function is called the application crashes, this happens with the production build but with the development build it doesn't happen. from iOS 17 and above this doesn't happen.

ERROR DETECTED ON iOS 16.7 AND iOS 16.6.1

Some logs:

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x2838 objc_msgSend + 56
1  MyNight                        0x8d8c outlined destroy of Any? + 4363029900 (<compiler-generated>:4363029900)
2  MyNight                        0x61034 ContextMenuInteractionWrapper.presentMenuAtLocation(point:) + 30 (ContextMenuInteractionWrapper.swift:30)
3  MyNight                        0x66b54 ContextMenuManager.presentMenu(atLocation:) + 138 (ContextMenuManager.swift:138)
4  MyNight                        0x587c44 RNIContextMenuView.presentMenu() + 629 (RNIContextMenuView.swift:629)
5  MyNight                        0x58f7c0 closure #1 in closure #4 in RNIContextMenuViewModule.definition() + 4368824256
6  MyNight                        0x590a04 partial apply for closure #1 in closure #5 in RNIContextMenuViewModule.definition() + 4368828932
7  MyNight                        0x42640 thunk for @escaping @callee_guaranteed () -> () + 4363265600 (<compiler-generated>:4363265600)
8  libdispatch.dylib              0x2320 _dispatch_call_block_and_release + 32
9  libdispatch.dylib              0x3eac _dispatch_client_callout + 20
10 libdispatch.dylib              0x126a4 _dispatch_main_queue_drain + 928
11 libdispatch.dylib              0x122f4 _dispatch_main_queue_callback_4CF + 44
12 CoreFoundation                 0x98c28 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
13 CoreFoundation                 0x7a560 __CFRunLoopRun + 1992
14 CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
15 GraphicsServices               0x135c GSEventRunModal + 164
16 UIKitCore                      0x39cf58 -[UIApplication _run] + 888
17 UIKitCore                      0x39cbbc UIApplicationMain + 340
18 MyNight                        0x48f8 main + 7 (main.m:7)
19 ???                            0x1cca84dec (Mancante)

**Comment by dominicstop** [comment]
Hi, unfortunately, this is because it's using a private API under the hood (and the specific API does not exist on that version of iOS)

I'm currently busy with `react-native-ios-adaptive-modal`, but i'll look into it. In the meantime, can you give me more debug-related info? 

I need to install an older version of Xcode, but i don't have enough space left (so i'm not able to fix this immediately).

the best i can do right now is prevent the crash from happening

**Comment by zeta-gc** [comment]
@dominicstop Hi, i dont have much info, i build the app with EAS [Expo Application Services]. 

more info about:

Dispositivo
Modello:iPhone 11
Orientamento:Verticale
RAM disponibile: 152.47 MB
Spazio libero su disco: 1.09 GB
Sistema operativo
Versione:16.6.1
Orientamento:Verticale
Con jailbreak:No
Arresto anomalo
Data:17 dic 2023, 23:28:36
Versione app:1.0.0 (8)


log provided by firebase crashlytics

**Comment by zeta-gc** [comment]
@dominicstop Could you tell me which iOS version has this feature? So i can handle the crash

**Comment by dominicstop** [comment]
@zeta-gc hi, i've pushed a new [commit](https://github.com/dominicstop/DGSwiftUtilities/commit/b21339aa24a48970e06d4f01b73b2bbba713fa5a) containing a potential fix for this issue, and released [new patch (version `0.8.2`)](https://github.com/dominicstop/DGSwiftUtilities/releases/tag/0.8.2) of [`DGSwiftUtilities`](https://cocoapods.org/pods/DGSwiftUtilities)

this library uses `DGSwiftUtilities` for invoking the private API that allows for programmatically showing the context menu.

It'll take some time before the new version appears on cocoapods. can you test if this fixes the bug?

**Comment by zeta-gc** [comment]
@dominicstop tested right now, it works perferctly now. THANKS FOR YOUR WORK <3
